version: '3.8'
services:
  flowers-database:
    image: postgres:alpine
    container_name: flowers-database
    ports:
      - "6001:5432"  # Exposing port 5432 of PostgreSQL to 6001 on host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring-2024
    volumes:
      - flowers-data:/var/lib/postgresql/data

volumes:
  flowers-data:
