spring:
  datasource:
    url: jdbc:postgresql://dpg-coks2mq0si5c73e0b0j0-a.oregon-postgres.render.com/cs322
    username: username
    password: FtD2VUn3QwKoANHXs9N9xrzWNx3IQvIR
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
