name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Updated distribution here

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push the Docker image
        run: |
          docker build -t ghcr.io/jsinnett23/flowerservice:latest --file Dockerfile .
          docker push ghcr.io/jsinnett23/flowerservice:latest
